name: run-tests
on: [push]
jobs:
  run-tests:
    runs-on: ubuntu-linux
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install
      - run: npm run test